title: 'Honolulu Bitcoin Developers'
tagline: 'Honolulu Bitcoin Developers is a meetup devoted to the research, development, and adoption of Bitcoin'

menu:
  - {name: 'About', url: '/about'}
  - {name: 'Resources', url: '/resources'}
  - {name: 'Meetup', url: 'https://www.meetup.com/honolulu-bitdevs/', external: true}
